### ISSUE TITLE
[BUG] Server crashes when booting with Linking Books installed.

### ISSUE THREAD

**Issue by Gbergz** [TheFloydman/linking-books#2]
**What version of *Linking Books* are you using?**
0.7.2.1

**What version of *NeoForge* are you using?**
21.1.83

**What version of *Minecraft* are you using?**
1.21.1

**What modpack and modpack version are you using, if any?**
None as of now. Indev modpack.

**Paste a link to your log or crash report here. Use a service like GitHub Gist. No images, please.**
https://gist.githubusercontent.com/Gbergz/6c3abb7347fc0a0dccbbbe4fdb16f194/raw/d837e2bcda2d3939774cb26901aea34c5ec5ba85/gistfile1.txt

**Describe the bug**
Server crash when booting

**To Reproduce**
1. Make a server.
2. Add mod.
3. Start server
4. Crash.

**Expected behavior**
No server crash.

**Screenshots**
*No response*

**Additional context**
*No response*

**Comment by TheFloydman** [comment]
Thank you for sharing. I've done a variety of tests on a server environment to make sure things are stable now. Hopefully v0.8.0.0 should solve any problems. [Modrinth](https://modrinth.com/mod/linkingbooks/version/1.21.1-0.8.0.0) [CurseForge](https://www.curseforge.com/minecraft/mc-mods/linkingbooks/files/5966903)
